ports:
  - port: 3000
    onOpen: open-browser
tasks:
  - init: npm install
    command: |
      export HMR_HOST=`gp url 3000`
      npm run dev
vscode:
  extensions:
    - bradlc.vscode-tailwindcss
    - esbenp.prettier-vscode
